// Country and flag resolver for market-risk portfolio data.
// Generated from ISO country metadata; keys are normalized ASCII aliases.

String marketCountrySearchKey(String value) {
  return value
      .toLowerCase()
      .replaceAll('à', 'a')
      .replaceAll('â', 'a')
      .replaceAll('ä', 'a')
      .replaceAll('á', 'a')
      .replaceAll('ã', 'a')
      .replaceAll('å', 'a')
      .replaceAll('é', 'e')
      .replaceAll('è', 'e')
      .replaceAll('ê', 'e')
      .replaceAll('ë', 'e')
      .replaceAll('í', 'i')
      .replaceAll('ì', 'i')
      .replaceAll('î', 'i')
      .replaceAll('ï', 'i')
      .replaceAll('ó', 'o')
      .replaceAll('ò', 'o')
      .replaceAll('ô', 'o')
      .replaceAll('ö', 'o')
      .replaceAll('õ', 'o')
      .replaceAll('ú', 'u')
      .replaceAll('ù', 'u')
      .replaceAll('û', 'u')
      .replaceAll('ü', 'u')
      .replaceAll('ý', 'y')
      .replaceAll('ÿ', 'y')
      .replaceAll('ñ', 'n')
      .replaceAll('ç', 'c')
      .replaceAll(RegExp(r'[\u2019\u2018]'), "'")
      .replaceAll(RegExp(r'[^a-z0-9]+'), ' ')
      .trim()
      .replaceAll(RegExp(r'\s+'), ' ');
}

String marketCountryIso3FromText(String country) {
  final normalized = marketCountrySearchKey(country);
  if (normalized.isEmpty) return '';
  return marketCountryIso3ByAlias[normalized] ?? '';
}

String marketCountryIso3FromLooseText(String value) {
  final exact = marketCountryIso3FromText(value);
  if (exact.isNotEmpty) return exact;

  final upperValue = value.toUpperCase();
  final isoMatch = RegExp(r'\(([A-Z]{3})\)').firstMatch(upperValue);
  if (isoMatch != null) {
    final iso3 = isoMatch.group(1)!;
    if (marketCountryIso3ToIso2.containsKey(iso3)) return iso3;
  }

  final normalized = ' ${marketCountrySearchKey(value)} ';
  if (normalized.trim().isEmpty) return '';

  for (final entry in marketCountryIso3ByAlias.entries) {
    if (entry.key.length < 4) continue;
    if (normalized.contains(' ${entry.key} ')) return entry.value;
  }
  return '';
}

String? marketCountryIso2FromIso3(String iso3) {
  return marketCountryIso3ToIso2[iso3.trim().toUpperCase()];
}

String? marketCountryFlagAssetFromIso3(String iso3) {
  final iso2 = marketCountryIso2FromIso3(iso3);
  if (iso2 == null || iso2.isEmpty) return null;
  return 'assets/flags/${iso2.toLowerCase()}.svg';
}

const Map<String, String> marketCountryIso3ToIso2 = {
  'ABW': 'AW',
  'AFG': 'AF',
  'AGO': 'AO',
  'AIA': 'AI',
  'ALA': 'AX',
  'ALB': 'AL',
  'AND': 'AD',
  'ARE': 'AE',
  'ARG': 'AR',
  'ARM': 'AM',
  'ASM': 'AS',
  'ATA': 'AQ',
  'ATF': 'TF',
  'ATG': 'AG',
  'AUS': 'AU',
  'AUT': 'AT',
  'AZE': 'AZ',
  'BDI': 'BI',
  'BEL': 'BE',
  'BEN': 'BJ',
  'BES': 'BQ',
  'BFA': 'BF',
  'BGD': 'BD',
  'BGR': 'BG',
  'BHR': 'BH',
  'BHS': 'BS',
  'BIH': 'BA',
  'BLM': 'BL',
  'BLR': 'BY',
  'BLZ': 'BZ',
  'BMU': 'BM',
  'BOL': 'BO',
  'BRA': 'BR',
  'BRB': 'BB',
  'BRN': 'BN',
  'BTN': 'BT',
  'BVT': 'BV',
  'BWA': 'BW',
  'CAF': 'CF',
  'CAN': 'CA',
  'CCK': 'CC',
  'CHE': 'CH',
  'CHL': 'CL',
  'CHN': 'CN',
  'CIV': 'CI',
  'CMR': 'CM',
  'COD': 'CD',
  'COG': 'CG',
  'COK': 'CK',
  'COL': 'CO',
  'COM': 'KM',
  'CPV': 'CV',
  'CRI': 'CR',
  'CUB': 'CU',
  'CUW': 'CW',
  'CXR': 'CX',
  'CYM': 'KY',
  'CYP': 'CY',
  'CZE': 'CZ',
  'DEU': 'DE',
  'DJI': 'DJ',
  'DMA': 'DM',
  'DNK': 'DK',
  'DOM': 'DO',
  'DZA': 'DZ',
  'ECU': 'EC',
  'EGY': 'EG',
  'ERI': 'ER',
  'ESH': 'EH',
  'ESP': 'ES',
  'EST': 'EE',
  'ETH': 'ET',
  'FIN': 'FI',
  'FJI': 'FJ',
  'FLK': 'FK',
  'FRA': 'FR',
  'FRO': 'FO',
  'FSM': 'FM',
  'GAB': 'GA',
  'GBR': 'GB',
  'GEO': 'GE',
  'GGY': 'GG',
  'GHA': 'GH',
  'GIB': 'GI',
  'GIN': 'GN',
  'GLP': 'GP',
  'GMB': 'GM',
  'GNB': 'GW',
  'GNQ': 'GQ',
  'GRC': 'GR',
  'GRD': 'GD',
  'GRL': 'GL',
  'GTM': 'GT',
  'GUF': 'GF',
  'GUM': 'GU',
  'GUY': 'GY',
  'HKG': 'HK',
  'HMD': 'HM',
  'HND': 'HN',
  'HRV': 'HR',
  'HTI': 'HT',
  'HUN': 'HU',
  'IDN': 'ID',
  'IMN': 'IM',
  'IND': 'IN',
  'IOT': 'IO',
  'IRL': 'IE',
  'IRN': 'IR',
  'IRQ': 'IQ',
  'ISL': 'IS',
  'ISR': 'IL',
  'ITA': 'IT',
  'JAM': 'JM',
  'JEY': 'JE',
  'JOR': 'JO',
  'JPN': 'JP',
  'KAZ': 'KZ',
  'KEN': 'KE',
  'KGZ': 'KG',
  'KHM': 'KH',
  'KIR': 'KI',
  'KNA': 'KN',
  'KOR': 'KR',
  'KWT': 'KW',
  'LAO': 'LA',
  'LBN': 'LB',
  'LBR': 'LR',
  'LBY': 'LY',
  'LCA': 'LC',
  'LIE': 'LI',
  'LKA': 'LK',
  'LSO': 'LS',
  'LTU': 'LT',
  'LUX': 'LU',
  'LVA': 'LV',
  'MAC': 'MO',
  'MAF': 'MF',
  'MAR': 'MA',
  'MCO': 'MC',
  'MDA': 'MD',
  'MDG': 'MG',
  'MDV': 'MV',
  'MEX': 'MX',
  'MHL': 'MH',
  'MKD': 'MK',
  'MLI': 'ML',
  'MLT': 'MT',
  'MMR': 'MM',
  'MNE': 'ME',
  'MNG': 'MN',
  'MNP': 'MP',
  'MOZ': 'MZ',
  'MRT': 'MR',
  'MSR': 'MS',
  'MTQ': 'MQ',
  'MUS': 'MU',
  'MWI': 'MW',
  'MYS': 'MY',
  'MYT': 'YT',
  'NAM': 'NA',
  'NCL': 'NC',
  'NER': 'NE',
  'NFK': 'NF',
  'NGA': 'NG',
  'NIC': 'NI',
  'NIU': 'NU',
  'NLD': 'NL',
  'NOR': 'NO',
  'NPL': 'NP',
  'NRU': 'NR',
  'NZL': 'NZ',
  'OMN': 'OM',
  'PAK': 'PK',
  'PAN': 'PA',
  'PCN': 'PN',
  'PER': 'PE',
  'PHL': 'PH',
  'PLW': 'PW',
  'PNG': 'PG',
  'POL': 'PL',
  'PRI': 'PR',
  'PRK': 'KP',
  'PRT': 'PT',
  'PRY': 'PY',
  'PSE': 'PS',
  'PYF': 'PF',
  'QAT': 'QA',
  'REU': 'RE',
  'ROU': 'RO',
  'RUS': 'RU',
  'RWA': 'RW',
  'SAU': 'SA',
  'SDN': 'SD',
  'SEN': 'SN',
  'SGP': 'SG',
  'SGS': 'GS',
  'SHN': 'SH',
  'SJM': 'SJ',
  'SLB': 'SB',
  'SLE': 'SL',
  'SLV': 'SV',
  'SMR': 'SM',
  'SOM': 'SO',
  'SPM': 'PM',
  'SRB': 'RS',
  'SSD': 'SS',
  'STP': 'ST',
  'SUR': 'SR',
  'SVK': 'SK',
  'SVN': 'SI',
  'SWE': 'SE',
  'SWZ': 'SZ',
  'SXM': 'SX',
  'SYC': 'SC',
  'SYR': 'SY',
  'TCA': 'TC',
  'TCD': 'TD',
  'TGO': 'TG',
  'THA': 'TH',
  'TJK': 'TJ',
  'TKL': 'TK',
  'TKM': 'TM',
  'TLS': 'TL',
  'TON': 'TO',
  'TTO': 'TT',
  'TUN': 'TN',
  'TUR': 'TR',
  'TUV': 'TV',
  'TWN': 'TW',
  'TZA': 'TZ',
  'UGA': 'UG',
  'UKR': 'UA',
  'UMI': 'UM',
  'UNK': 'XK',
  'URY': 'UY',
  'USA': 'US',
  'UZB': 'UZ',
  'VAT': 'VA',
  'VCT': 'VC',
  'VEN': 'VE',
  'VGB': 'VG',
  'VIR': 'VI',
  'VNM': 'VN',
  'VUT': 'VU',
  'WLF': 'WF',
  'WSM': 'WS',
  'YEM': 'YE',
  'ZAF': 'ZA',
  'ZMB': 'ZM',
  'ZWE': 'ZW',
};

const Map<String, String> marketCountryIso3ByAlias = {
  'aaland': 'ALA',
  'abw': 'ABW',
  'ad': 'AND',
  'ae': 'ARE',
  'af': 'AFG',
  'afg': 'AFG',
  'afganistan': 'AFG',
  'afghanistan': 'AFG',
  'afrique du sud': 'ZAF',
  'ag': 'ATG',
  'ago': 'AGO',
  'ahvenanmaa': 'ALA',
  'ai': 'AIA',
  'aia': 'AIA',
  'al': 'ALB',
  'al ittihad al qumuri': 'COM',
  'al jumhuriyah al arabiyah as suriyah': 'SYR',
  'al jumhuriyah al libnaniyah': 'LBN',
  'al jumhuriyyah al islamiyyah al muritaniyyah': 'MRT',
  'al jumhuriyyah al yamaniyyah': 'YEM',
  'al jumhuriyyah at tunisiyyah': 'TUN',
  'al mamlakah al arabiyyah as su udiyyah': 'SAU',
  'al mamlakah al magribiyah': 'MAR',
  'al mamlakah al urduniyah al hashimiyah': 'JOR',
  'ala': 'ALA',
  'aland': 'ALA',
  'aland islands': 'ALA',
  'alb': 'ALB',
  'albania': 'ALB',
  'albanie': 'ALB',
  'algeria': 'DZA',
  'algerie': 'DZA',
  'allemagne': 'DEU',
  'am': 'ARM',
  'amelika samoa': 'ASM',
  'american samoa': 'ASM',
  'amerika samoa': 'ASM',
  'and': 'AND',
  'andorra': 'AND',
  'andorre': 'AND',
  'angola': 'AGO',
  'anguilla': 'AIA',
  'antarctica': 'ATA',
  'antarctique': 'ATA',
  'antigua and barbuda': 'ATG',
  'antigua et barbuda': 'ATG',
  'ao': 'AGO',
  'aolepan aorokin majel': 'MHL',
  'aotearoa': 'NZL',
  'aq': 'ATA',
  'ar': 'ARG',
  'arab republic of egypt': 'EGY',
  'arabie saoudite': 'SAU',
  'are': 'ARE',
  'arg': 'ARG',
  'argentina': 'ARG',
  'argentine': 'ARG',
  'argentine republic': 'ARG',
  'arm': 'ARM',
  'armenia': 'ARM',
  'armenie': 'ARM',
  'aruba': 'ABW',
  'as': 'ASM',
  'as sumal': 'SOM',
  'asm': 'ASM',
  'at': 'AUT',
  'ata': 'ATA',
  'atf': 'ATF',
  'atg': 'ATG',
  'au': 'AUS',
  'aus': 'AUS',
  'australia': 'AUS',
  'australie': 'AUS',
  'austria': 'AUT',
  'aut': 'AUT',
  'autriche': 'AUT',
  'aw': 'ABW',
  'ax': 'ALA',
  'az': 'AZE',
  'az rbaycan respublikas': 'AZE',
  'aze': 'AZE',
  'azerbaidjan': 'AZE',
  'azerbaijan': 'AZE',
  'ba': 'BIH',
  'bahamas': 'BHS',
  'bahrain': 'BHR',
  'bahrein': 'BHR',
  'bailiwick of guernsey': 'GGY',
  'bailiwick of jersey': 'JEY',
  'bailliage de guernesey': 'GGY',
  'bailliage de jerri': 'JEY',
  'bailliage de jersey': 'JEY',
  'bangladesh': 'BGD',
  'barbade': 'BRB',
  'barbados': 'BRB',
  'bb': 'BRB',
  'bd': 'BGD',
  'bdi': 'BDI',
  'be': 'BEL',
  'bel': 'BEL',
  'belarus': 'BLR',
  'belgie': 'BEL',
  'belgien': 'BEL',
  'belgique': 'BEL',
  'belgium': 'BEL',
  'belize': 'BLZ',
  'beluu er a belau': 'PLW',
  'ben': 'BEN',
  'benin': 'BEN',
  'bermuda': 'BMU',
  'bermudes': 'BMU',
  'bes': 'BES',
  'bes islands': 'BES',
  'bf': 'BFA',
  'bfa': 'BFA',
  'bg': 'BGR',
  'bgd': 'BGD',
  'bgr': 'BGR',
  'bh': 'BHR',
  'bharat': 'IND',
  'bharat ganrajya': 'IND',
  'bhoutan': 'BTN',
  'bhr': 'BHR',
  'bhs': 'BHS',
  'bhutan': 'BTN',
  'bi': 'BDI',
  'bielarus': 'BLR',
  'bielorussie': 'BLR',
  'bih': 'BIH',
  'birmanie': 'MMR',
  'bj': 'BEN',
  'bl': 'BLM',
  'blm': 'BLM',
  'blr': 'BLR',
  'blz': 'BLZ',
  'bm': 'BMU',
  'bmu': 'BMU',
  'bn': 'BRN',
  'bo': 'BOL',
  'bol': 'BOL',
  'bolivarian republic of venezuela': 'VEN',
  'bolivia': 'BOL',
  'bolivia plurinational state of': 'BOL',
  'bolivie': 'BOL',
  'bonaire saint eustache et saba': 'BES',
  'bonaire sint eustatius and saba': 'BES',
  'bosnia and herzegovina': 'BIH',
  'bosnia herzegovina': 'BIH',
  'bosnie et herzegovine': 'BIH',
  'bosnie herzegovine': 'BIH',
  'botswana': 'BWA',
  'bouvet island': 'BVT',
  'bouvet ya': 'BVT',
  'bq': 'BES',
  'br': 'BRA',
  'bra': 'BRA',
  'brasil': 'BRA',
  'brazil': 'BRA',
  'brb': 'BRB',
  'bresil': 'BRA',
  'british indian ocean territory': 'IOT',
  'british virgin islands': 'VGB',
  'brn': 'BRN',
  'brunei': 'BRN',
  'brunei darussalam': 'BRN',
  'bs': 'BHS',
  'bt': 'BTN',
  'btn': 'BTN',
  'bulgaria': 'BGR',
  'bulgarie': 'BGR',
  'buliwya': 'BOL',
  'buliwya mamallaqta': 'BOL',
  'bundesrepublik deutschland': 'DEU',
  'burkina': 'BFA',
  'burkina faso': 'BFA',
  'burma': 'MMR',
  'burundi': 'BDI',
  'bv': 'BVT',
  'bvt': 'BVT',
  'bw': 'BWA',
  'bwa': 'BWA',
  'by': 'BLR',
  'bz': 'BLZ',
  'ca': 'CAN',
  'cabo verde': 'CPV',
  'caf': 'CAF',
  'cambodge': 'KHM',
  'cambodia': 'KHM',
  'cameroon': 'CMR',
  'cameroun': 'CMR',
  'can': 'CAN',
  'canada': 'CAN',
  'cap vert': 'CPV',
  'cape verde': 'CPV',
  'caribbean netherlands': 'BES',
  'cayman islands': 'CYM',
  'cc': 'CCK',
  'cck': 'CCK',
  'cd': 'COD',
  'centrafrique': 'CAF',
  'central african republic': 'CAF',
  'ceska republika': 'CZE',
  'cesko': 'CZE',
  'cf': 'CAF',
  'cg': 'COG',
  'ch': 'CHE',
  'chad': 'TCD',
  'che': 'CHE',
  'chile': 'CHL',
  'chili': 'CHL',
  'china': 'CHN',
  'chine': 'CHN',
  'chinese taipei': 'TWN',
  'chl': 'CHL',
  'chn': 'CHN',
  'choson minjujuui inmin konghwaguk': 'PRK',
  'christmas island': 'CXR',
  'chypre': 'CYP',
  'ci': 'CIV',
  'cite du vatican': 'VAT',
  'civ': 'CIV',
  'ck': 'COK',
  'cl': 'CHL',
  'cm': 'CMR',
  'cmr': 'CMR',
  'cn': 'CHN',
  'co': 'COL',
  'co operative republic of guyana': 'GUY',
  'cocos islands': 'CCK',
  'cocos keeling islands': 'CCK',
  'cod': 'COD',
  'cog': 'COG',
  'cok': 'COK',
  'col': 'COL',
  'collectivite de saint barthelemy': 'BLM',
  'collectivite de saint martin': 'MAF',
  'collectivite territoriale de saint pierre et miquelon': 'SPM',
  'collectivity of saint barthelemy': 'BLM',
  'collectivity of saint martin': 'MAF',
  'colombia': 'COL',
  'colombie': 'COL',
  'com': 'COM',
  'commonwealth de la dominique': 'DMA',
  'commonwealth des bahamas': 'BHS',
  'commonwealth des iles mariannes du nord': 'MNP',
  'commonwealth of australia': 'AUS',
  'commonwealth of dominica': 'DMA',
  'commonwealth of puerto rico': 'PRI',
  'commonwealth of the bahamas': 'BHS',
  'commonwealth of the northern mariana islands': 'MNP',
  'comores': 'COM',
  'comoros': 'COM',
  'confederation suisse': 'CHE',
  'cong hoa xa hoi chu nghia viet nam': 'VNM',
  'congo': 'COG',
  'congo brazzaville': 'COG',
  'congo kinshasa': 'COD',
  'congo rep dem': 'COD',
  'congo republic': 'COG',
  'congo the democratic republic of the': 'COD',
  'cook islands': 'COK',
  'coree du nord': 'PRK',
  'coree du sud': 'KOR',
  'coree nord': 'PRK',
  'coree sud': 'KOR',
  'costa rica': 'CRI',
  'cote d ivoire': 'CIV',
  'cote divoire': 'CIV',
  'country of curacao': 'CUW',
  'cpv': 'CPV',
  'cr': 'CRI',
  'cri': 'CRI',
  'crna gora': 'MNE',
  'croatia': 'HRV',
  'croatie': 'HRV',
  'cu': 'CUB',
  'cub': 'CUB',
  'cuba': 'CUB',
  'cumhuriyi tocikiston': 'TJK',
  'curacao': 'CUW',
  'cuw': 'CUW',
  'cv': 'CPV',
  'cw': 'CUW',
  'cx': 'CXR',
  'cxr': 'CXR',
  'cy': 'CYP',
  'cym': 'CYM',
  'cyp': 'CYP',
  'cyprus': 'CYP',
  'cz': 'CZE',
  'cze': 'CZE',
  'czech republic': 'CZE',
  'czechia': 'CZE',
  'danemark': 'DNK',
  'danmark': 'DNK',
  'dawlat al kuwait': 'KWT',
  'dawlat filastin': 'PSE',
  'dawlat iritriya': 'ERI',
  'dawlat libya': 'LBY',
  'dawlat qatar': 'QAT',
  'de': 'DEU',
  'democratic people s republic of korea': 'PRK',
  'democratic republic of sao tome and principe': 'STP',
  'democratic republic of the congo': 'COD',
  'democratic republic of timor leste': 'TLS',
  'democratic socialist republic of sri lanka': 'LKA',
  'denmark': 'DNK',
  'departement de mayotte': 'MYT',
  'department of mayotte': 'MYT',
  'des iles heard et mcdonald': 'HMD',
  'deu': 'DEU',
  'dhivehi raajjeyge jumhooriyya': 'MDV',
  'dj': 'DJI',
  'dji': 'DJI',
  'djibouti': 'DJI',
  'dk': 'DNK',
  'dm': 'DMA',
  'dma': 'DMA',
  'dnk': 'DNK',
  'do': 'DOM',
  'dom': 'DOM',
  'dominica': 'DMA',
  'dominican republic': 'DOM',
  'dominique': 'DMA',
  'dprk': 'PRK',
  'dr congo': 'COD',
  'drc': 'COD',
  'dz': 'DZA',
  'dza': 'DZA',
  'dzayer': 'DZA',
  'east timor': 'TLS',
  'ec': 'ECU',
  'ecu': 'ECU',
  'ecuador': 'ECU',
  'ee': 'EST',
  'eesti': 'EST',
  'eesti vabariik': 'EST',
  'eg': 'EGY',
  'egy': 'EGY',
  'egypt': 'EGY',
  'egypte': 'EGY',
  'eh': 'ESH',
  'eire': 'IRL',
  'el salvador': 'SLV',
  'ellada': 'GRC',
  'ellan vannin': 'IMN',
  'emirates': 'ARE',
  'emirats arabes unis': 'ARE',
  'equateur': 'ECU',
  'equatorial guinea': 'GNQ',
  'er': 'ERI',
  'eri': 'ERI',
  'eritrea': 'ERI',
  'ertra': 'ERI',
  'erythree': 'ERI',
  'es': 'ESP',
  'esh': 'ESH',
  'esp': 'ESP',
  'espagne': 'ESP',
  'est': 'EST',
  'estado libre asociado de puerto rico': 'PRI',
  'estado plurinacional de bolivia': 'BOL',
  'estados unidos mexicanos': 'MEX',
  'estonia': 'EST',
  'estonie': 'EST',
  'eswatini': 'SWZ',
  'et': 'ETH',
  'etat d erythree': 'ERI',
  'etat d israel': 'ISR',
  'etat de brunei darussalam': 'BRN',
  'etat de palestine': 'PSE',
  'etat du koweit': 'KWT',
  'etat du qatar': 'QAT',
  'etat independant de papouasie nouvelle guinee': 'PNG',
  'etat plurinational de bolivie': 'BOL',
  'etat unis': 'USA',
  'etats federes de micronesie': 'FSM',
  'etats unis': 'USA',
  'etats unis du mexique': 'MEX',
  'eth': 'ETH',
  'ethiopia': 'ETH',
  'ethiopie': 'ETH',
  'f r erne': 'FRO',
  'f royar': 'FRO',
  'falkland islands': 'FLK',
  'falkland islands malvinas': 'FLK',
  'faroe islands': 'FRO',
  'federal democratic republic of ethiopia': 'ETH',
  'federal democratic republic of nepal': 'NPL',
  'federal republic of germany': 'DEU',
  'federal republic of nigeria': 'NGA',
  'federal republic of somalia': 'SOM',
  'federated states of micronesia': 'FSM',
  'federation de malaisie': 'MYS',
  'federation de russie': 'RUS',
  'federation de saint christophe et nieves': 'KNA',
  'federation of saint christopher and nevis': 'KNA',
  'federative republic of brazil': 'BRA',
  'fi': 'FIN',
  'fidji': 'FJI',
  'fiji': 'FJI',
  'fiji ganarajya': 'FJI',
  'fin': 'FIN',
  'finland': 'FIN',
  'finlande': 'FIN',
  'fj': 'FJI',
  'fji': 'FJI',
  'fk': 'FLK',
  'flk': 'FLK',
  'fm': 'FSM',
  'fo': 'FRO',
  'fr': 'FRA',
  'fra': 'FRA',
  'france': 'FRA',
  'french guiana': 'GUF',
  'french polynesia': 'PYF',
  'french republic': 'FRA',
  'french southern and antarctic lands': 'ATF',
  'french southern territories': 'ATF',
  'fro': 'FRO',
  'fsm': 'FSM',
  'furstentum liechtenstein': 'LIE',
  'ga': 'GAB',
  'gab': 'GAB',
  'gabon': 'GAB',
  'gabonese republic': 'GAB',
  'gabuuti': 'DJI',
  'gabuutih ummuuno': 'DJI',
  'gambia': 'GMB',
  'gambie': 'GMB',
  'gb': 'GBR',
  'gbr': 'GBR',
  'gd': 'GRD',
  'ge': 'GEO',
  'geo': 'GEO',
  'georgia': 'GEO',
  'georgie': 'GEO',
  'georgie du sud et les iles sandwich du sud': 'SGS',
  'germany': 'DEU',
  'gf': 'GUF',
  'gg': 'GGY',
  'ggy': 'GGY',
  'gh': 'GHA',
  'gha': 'GHA',
  'ghana': 'GHA',
  'gi': 'GIB',
  'gib': 'GIB',
  'gibraltar': 'GIB',
  'gin': 'GIN',
  'gl': 'GRL',
  'glp': 'GLP',
  'gm': 'GMB',
  'gmb': 'GMB',
  'gn': 'GIN',
  'gnb': 'GNB',
  'gnq': 'GNQ',
  'gonoprojatontri bangladesh': 'BGD',
  'gp': 'GLP',
  'gq': 'GNQ',
  'gr': 'GRC',
  'gr nland': 'GRL',
  'grand duche de luxembourg': 'LUX',
  'grand duchy of luxembourg': 'LUX',
  'grande bretagne': 'GBR',
  'grande republique arabe libyenne populaire et socialiste': 'LBY',
  'grc': 'GRC',
  'grd': 'GRD',
  'great britain': 'GBR',
  'grece': 'GRC',
  'greece': 'GRC',
  'greenland': 'GRL',
  'grenada': 'GRD',
  'grenade': 'GRD',
  'grl': 'GRL',
  'gro herzogtum luxemburg': 'LUX',
  'groenland': 'GRL',
  'groupe d iles pitcairn': 'PCN',
  'groussherzogtum letzebuerg': 'LUX',
  'gs': 'SGS',
  'gt': 'GTM',
  'gtm': 'GTM',
  'gu': 'GUM',
  'guadeloupe': 'GLP',
  'guahan': 'GUM',
  'guam': 'GUM',
  'guatemala': 'GTM',
  'guernesey': 'GGY',
  'guernsey': 'GGY',
  'guf': 'GUF',
  'guiana': 'GUF',
  'guinea': 'GIN',
  'guinea bissau': 'GNB',
  'guinea conakry': 'GIN',
  'guinee': 'GIN',
  'guinee bissau': 'GNB',
  'guinee conakry': 'GIN',
  'guinee equatoriale': 'GNQ',
  'gum': 'GUM',
  'guy': 'GUY',
  'guyana': 'GUY',
  'guyane': 'GUF',
  'gw': 'GNB',
  'gwadloup': 'GLP',
  'gy': 'GUY',
  'haiti': 'HTI',
  'hashemite kingdom of jordan': 'JOR',
  'hayastan': 'ARM',
  'heard island and mcdonald islands': 'HMD',
  'hellenic republic': 'GRC',
  'hk': 'HKG',
  'hkg': 'HKG',
  'hm': 'HMD',
  'hmd': 'HMD',
  'hn': 'HND',
  'hnd': 'HND',
  'holland': 'NLD',
  'holy see vatican city state': 'VAT',
  'honduras': 'HND',
  'hong kong': 'HKG',
  'hong kong special administrative region of the people s republic of china':
      'HKG',
  'hongrie': 'HUN',
  'hr': 'HRV',
  'hrv': 'HRV',
  'hrvatska': 'HRV',
  'ht': 'HTI',
  'hti': 'HTI',
  'hu': 'HUN',
  'hun': 'HUN',
  'hungary': 'HUN',
  'iceland': 'ISL',
  'id': 'IDN',
  'idn': 'IDN',
  'ie': 'IRL',
  'il': 'ISR',
  'ilankai': 'LKA',
  'ile bouvet': 'BVT',
  'ile christmas': 'CXR',
  'ile de la reunion': 'REU',
  'ile de man': 'IMN',
  'ile maurice': 'MUS',
  'ile norfolk': 'NFK',
  'iles caimans': 'CYM',
  'iles cocos': 'CCK',
  'iles cook': 'COK',
  'iles du cap vert': 'CPV',
  'iles feroe': 'FRO',
  'iles heard et macdonald': 'HMD',
  'iles malouines': 'FLK',
  'iles mariannes du nord': 'MNP',
  'iles marshall': 'MHL',
  'iles mineures eloignees des etats unis': 'UMI',
  'iles pitcairn': 'PCN',
  'iles salomon': 'SLB',
  'iles tokelau': 'TKL',
  'iles turques et caiques': 'TCA',
  'iles vierges': 'VGB',
  'iles vierges britanniques': 'VGB',
  'iles vierges des etats unis': 'VIR',
  'im': 'IMN',
  'imn': 'IMN',
  'in': 'IND',
  'ind': 'IND',
  'inde': 'IND',
  'independen stet bilong papua niugini': 'PNG',
  'independent and sovereign republic of kiribati': 'KIR',
  'independent state of papua new guinea': 'PNG',
  'independent state of samoa': 'WSM',
  'india': 'IND',
  'indonesia': 'IDN',
  'indonesie': 'IDN',
  'io': 'IOT',
  'iot': 'IOT',
  'iq': 'IRQ',
  'ir': 'IRN',
  'irak': 'IRQ',
  'iran': 'IRN',
  'iran islamic republic of': 'IRN',
  'iraq': 'IRQ',
  'ireland': 'IRL',
  'iritriya': 'ERI',
  'irl': 'IRL',
  'irlande': 'IRL',
  'irn': 'IRN',
  'irq': 'IRQ',
  'is': 'ISL',
  'isl': 'ISL',
  'islami jumhuriya eh pakistan': 'PAK',
  'islamic republic of afghanistan': 'AFG',
  'islamic republic of iran': 'IRN',
  'islamic republic of mauritania': 'MRT',
  'islamic republic of pakistan': 'PAK',
  'island': 'ISL',
  'islande': 'ISL',
  'islas malvinas': 'FLK',
  'isle of man': 'IMN',
  'isr': 'ISR',
  'israel': 'ISR',
  'it': 'ITA',
  'ita': 'ITA',
  'italian republic': 'ITA',
  'italie': 'ITA',
  'italy': 'ITA',
  'ityoppya': 'ETH',
  'ivoire': 'CIV',
  'ivory coast': 'CIV',
  'jabuuti': 'DJI',
  'jam': 'JAM',
  'jamaica': 'JAM',
  'jamaique': 'JAM',
  'jamhuri ya kenya': 'KEN',
  'jamhuri ya muungano wa tanzania': 'TZA',
  'jamhuri ya uganda': 'UGA',
  'jamhuuriyadda federaalka soomaaliya': 'SOM',
  'jamhuuriyadda jabuuti': 'DJI',
  'jan mayen svalbard': 'SJM',
  'japan': 'JPN',
  'japon': 'JPN',
  'je': 'JEY',
  'jersey': 'JEY',
  'jey': 'JEY',
  'jm': 'JAM',
  'jo': 'JOR',
  'jomhuri ye eslami ye iran': 'IRN',
  'jor': 'JOR',
  'jordan': 'JOR',
  'jordanie': 'JOR',
  'jp': 'JPN',
  'jpn': 'JPN',
  'jumhuriyat as sudan': 'SDN',
  'jumhuriyyat al iraq': 'IRQ',
  'jumhuriyyat as sumal al fideraliyya': 'SOM',
  'k br s': 'CYP',
  'k br s cumhuriyeti': 'CYP',
  'kaz': 'KAZ',
  'kazakhstan': 'KAZ',
  'ke': 'KEN',
  'keeling islands': 'CCK',
  'ken': 'KEN',
  'kenya': 'KEN',
  'kg': 'KGZ',
  'kgz': 'KGZ',
  'kh': 'KHM',
  'khm': 'KHM',
  'ki': 'KIR',
  'kingdom of bahrain': 'BHR',
  'kingdom of belgium': 'BEL',
  'kingdom of bhutan': 'BTN',
  'kingdom of cambodia': 'KHM',
  'kingdom of denmark': 'DNK',
  'kingdom of eswatini': 'SWZ',
  'kingdom of lesotho': 'LSO',
  'kingdom of morocco': 'MAR',
  'kingdom of norway': 'NOR',
  'kingdom of saudi arabia': 'SAU',
  'kingdom of spain': 'ESP',
  'kingdom of sweden': 'SWE',
  'kingdom of thailand': 'THA',
  'kingdom of the netherlands': 'NLD',
  'kingdom of tonga': 'TON',
  'kir': 'KIR',
  'kirghizistan': 'KGZ',
  'kiribati': 'KIR',
  'km': 'COM',
  'kn': 'KNA',
  'kna': 'KNA',
  'kongeriget danmark': 'DNK',
  'kongeriket noreg': 'NOR',
  'kongeriket norge': 'NOR',
  'konigreich belgien': 'BEL',
  'koninkrijk belgie': 'BEL',
  'konungariket sverige': 'SWE',
  'kor': 'KOR',
  'korea democratic people s republic of': 'PRK',
  'korea republic of': 'KOR',
  'korsou': 'CUW',
  'kosovo': 'UNK',
  'koweit': 'KWT',
  'kp': 'PRK',
  'kr': 'KOR',
  'kuki airani': 'COK',
  'kuwait': 'KWT',
  'kw': 'KWT',
  'kwt': 'KWT',
  'ky': 'CYM',
  'kypros': 'CYP',
  'kyrgyz republic': 'KGZ',
  'kyrgyz respublikasy': 'KGZ',
  'kyrgyzstan': 'KGZ',
  'kz': 'KAZ',
  'la': 'LAO',
  'la republique populaire du bangladesh': 'BGD',
  'land curacao': 'CUW',
  'lao': 'LAO',
  'lao people s democratic republic': 'LAO',
  'laos': 'LAO',
  'latvia': 'LVA',
  'latvijas republika': 'LVA',
  'lb': 'LBN',
  'lbn': 'LBN',
  'lbr': 'LBR',
  'lby': 'LBY',
  'lc': 'LCA',
  'lca': 'LCA',
  'lebanese republic': 'LBN',
  'lebanon': 'LBN',
  'lefatshe la botswana': 'BWA',
  'les etats unis d amerique': 'USA',
  'lesotho': 'LSO',
  'lettonie': 'LVA',
  'li': 'LIE',
  'liban': 'LBN',
  'liberia': 'LBR',
  'libya': 'LBY',
  'libye': 'LBY',
  'lie': 'LIE',
  'liechtenstein': 'LIE',
  'lietuvos respublika': 'LTU',
  'lithuania': 'LTU',
  'lituanie': 'LTU',
  'lk': 'LKA',
  'lka': 'LKA',
  'loktantrik ganatantra nepal': 'NPL',
  'lr': 'LBR',
  'ls': 'LSO',
  'lso': 'LSO',
  'lt': 'LTU',
  'ltu': 'LTU',
  'lu': 'LUX',
  'lux': 'LUX',
  'luxembourg': 'LUX',
  'lv': 'LVA',
  'lva': 'LVA',
  'ly': 'LBY',
  'ly veldi island': 'ISL',
  'ma': 'MAR',
  'mac': 'MAC',
  'macao': 'MAC',
  'macao special administrative region of the people s republic of china':
      'MAC',
  'macau': 'MAC',
  'macedoine du nord': 'MKD',
  'macedonia the former yugoslav republic of': 'MKD',
  'madagascar': 'MDG',
  'maf': 'MAF',
  'malaisie': 'MYS',
  'malawi': 'MWI',
  'malaysia': 'MYS',
  'maldive islands': 'MDV',
  'maldives': 'MDV',
  'mali': 'MLI',
  'malo sa oloto tuto atasi o samoa': 'WSM',
  'malta': 'MLT',
  'malte': 'MLT',
  'mamlakat al bahrayn': 'BHR',
  'mann': 'IMN',
  'mannin': 'IMN',
  'mar': 'MAR',
  'maroc': 'MAR',
  'marshall islands': 'MHL',
  'martinique': 'MTQ',
  'matanitu ko viti': 'FJI',
  'mauritania': 'MRT',
  'mauritanie': 'MRT',
  'mauritius': 'MUS',
  'mayotte': 'MYT',
  'mc': 'MCO',
  'mco': 'MCO',
  'md': 'MDA',
  'mda': 'MDA',
  'mdg': 'MDG',
  'mdv': 'MDV',
  'me': 'MNE',
  'medinat yisra el': 'ISR',
  'mex': 'MEX',
  'mexicanos': 'MEX',
  'mexico': 'MEX',
  'mexique': 'MEX',
  'mf': 'MAF',
  'mg': 'MDG',
  'mh': 'MHL',
  'mhl': 'MHL',
  'micronesia': 'FSM',
  'micronesia federated states of': 'FSM',
  'micronesie': 'FSM',
  'mk': 'MKD',
  'mkd': 'MKD',
  'ml': 'MLI',
  'mli': 'MLI',
  'mlt': 'MLT',
  'mm': 'MMR',
  'mmr': 'MMR',
  'mn': 'MNG',
  'mne': 'MNE',
  'mng': 'MNG',
  'mnp': 'MNP',
  'mo': 'MAC',
  'moldavie': 'MDA',
  'moldova': 'MDA',
  'moldova republic of': 'MDA',
  'monaco': 'MCO',
  'mongolia': 'MNG',
  'mongolie': 'MNG',
  'montenegro': 'MNE',
  'montserrat': 'MSR',
  'morocco': 'MAR',
  'moz': 'MOZ',
  'mozambique': 'MOZ',
  'mp': 'MNP',
  'mq': 'MTQ',
  'mr': 'MRT',
  'mrt': 'MRT',
  'ms': 'MSR',
  'msr': 'MSR',
  'mt': 'MLT',
  'mtq': 'MTQ',
  'mu': 'MUS',
  'mus': 'MUS',
  'muso oa lesotho': 'LSO',
  'mv': 'MDV',
  'mw': 'MWI',
  'mwi': 'MWI',
  'mx': 'MEX',
  'my': 'MYS',
  'myanmar': 'MMR',
  'mys': 'MYS',
  'myt': 'MYT',
  'mz': 'MOZ',
  'na': 'NAM',
  'naijiria': 'NGA',
  'nam': 'NAM',
  'namibia': 'NAM',
  'namibie': 'NAM',
  'naoero': 'NRU',
  'nation of brunei': 'BRN',
  'nation of brunei abode of peace': 'BRN',
  'nauru': 'NRU',
  'nc': 'NCL',
  'ncl': 'NCL',
  'ne': 'NER',
  'nederland': 'NLD',
  'nepal': 'NPL',
  'ner': 'NER',
  'netherlands': 'NLD',
  'new caledonia': 'NCL',
  'new zealand': 'NZL',
  'nf': 'NFK',
  'nfk': 'NFK',
  'ng': 'NGA',
  'nga': 'NGA',
  'ngwane': 'SWZ',
  'ni': 'NIC',
  'nic': 'NIC',
  'nicaragua': 'NIC',
  'niger': 'NER',
  'nigeria': 'NGA',
  'nihon': 'JPN',
  'nijar': 'NER',
  'nijeriya': 'NGA',
  'nippon': 'JPN',
  'niu': 'NIU',
  'niue': 'NIU',
  'nl': 'NLD',
  'nld': 'NLD',
  'no': 'NOR',
  'nor': 'NOR',
  'noreg': 'NOR',
  'norfolk island': 'NFK',
  'norge': 'NOR',
  'north korea': 'PRK',
  'north macedonia': 'MKD',
  'northern mariana islands': 'MNP',
  'norvege': 'NOR',
  'norway': 'NOR',
  'nouvelle caledonie': 'NCL',
  'nouvelle zelande': 'NZL',
  'np': 'NPL',
  'npl': 'NPL',
  'nr': 'NRU',
  'nru': 'NRU',
  'nu': 'NIU',
  'nz': 'NZL',
  'nzl': 'NZL',
  'o zbekiston respublikasi': 'UZB',
  'oesterreich': 'AUT',
  'om': 'OMN',
  'oman': 'OMN',
  'omn': 'OMN',
  'oriental republic of uruguay': 'URY',
  'osterreich': 'AUT',
  'ouganda': 'UGA',
  'ouzbekistan': 'UZB',
  'pa': 'PAN',
  'pais korsou': 'CUW',
  'pak': 'PAK',
  'pakistan': 'PAK',
  'palaos palau': 'PLW',
  'palau': 'PLW',
  'palestine': 'PSE',
  'palestine state of': 'PSE',
  'pan': 'PAN',
  'panama': 'PAN',
  'papouasie nouvelle guinee': 'PNG',
  'papua new guinea': 'PNG',
  'paraguay': 'PRY',
  'pays bas': 'NLD',
  'pays bas caribeens': 'BES',
  'pays de curacao': 'CUW',
  'pcn': 'PCN',
  'pe': 'PER',
  'people s democratic republic of algeria': 'DZA',
  'people s republic of bangladesh': 'BGD',
  'people s republic of china': 'CHN',
  'per': 'PER',
  'perou': 'PER',
  'peru': 'PER',
  'pf': 'PYF',
  'pg': 'PNG',
  'ph': 'PHL',
  'philippines': 'PHL',
  'phl': 'PHL',
  'pitcairn': 'PCN',
  'pitcairn group of islands': 'PCN',
  'pitcairn henderson ducie and oeno islands': 'PCN',
  'pitcairn islands': 'PCN',
  'pk': 'PAK',
  'pl': 'POL',
  'pleasant island': 'NRU',
  'plurinational state of bolivia': 'BOL',
  'plw': 'PLW',
  'pm': 'SPM',
  'pn': 'PCN',
  'png': 'PNG',
  'poblacht na heireann': 'IRL',
  'pol': 'POL',
  'poland': 'POL',
  'pologne': 'POL',
  'polynesie francaise': 'PYF',
  'porinetia farani': 'PYF',
  'porto rico': 'PRI',
  'portugal': 'PRT',
  'portuguesa': 'PRT',
  'portuguese republic': 'PRT',
  'pr': 'PRI',
  'prathet': 'THA',
  'pri': 'PRI',
  'principality of andorra': 'AND',
  'principality of liechtenstein': 'LIE',
  'principality of monaco': 'MCO',
  'principat d andorra': 'AND',
  'principaute d andorre': 'AND',
  'principaute de monaco': 'MCO',
  'principaute du liechtenstein': 'LIE',
  'prk': 'PRK',
  'prt': 'PRT',
  'pry': 'PRY',
  'ps': 'PSE',
  'pse': 'PSE',
  'pt': 'PRT',
  'publika de an la': 'AGO',
  'puerto rico': 'PRI',
  'pw': 'PLW',
  'py': 'PRY',
  'pyf': 'PYF',
  'pyidaunzu thanmada myama nainngandaw': 'MMR',
  'qa': 'QAT',
  'qat': 'QAT',
  'qatar': 'QAT',
  'qazaqstan': 'KAZ',
  'qazaqstan respublikas': 'KAZ',
  'ratcha anachak thai': 'THA',
  'rdc': 'COD',
  're': 'REU',
  'regiao administrativa especial de macau da republica popular da china':
      'MAC',
  'region administrative speciale de hong kong de la republique populaire de chine':
      'HKG',
  'region administrative speciale de macao de la republique populaire de chine':
      'MAC',
  'reino de espana': 'ESP',
  'repiblik ayiti': 'HTI',
  'repiblik sesel': 'SYC',
  'repoblikan i madagasikara': 'MDG',
  'repubblica di san marino': 'SMR',
  'repubblica italiana': 'ITA',
  'repubblika ta malta': 'MLT',
  'republic of albania': 'ALB',
  'republic of angola': 'AGO',
  'republic of armenia': 'ARM',
  'republic of austria': 'AUT',
  'republic of azerbaijan': 'AZE',
  'republic of belarus': 'BLR',
  'republic of benin': 'BEN',
  'republic of botswana': 'BWA',
  'republic of bulgaria': 'BGR',
  'republic of burundi': 'BDI',
  'republic of cabo verde': 'CPV',
  'republic of cameroon': 'CMR',
  'republic of chad': 'TCD',
  'republic of chile': 'CHL',
  'republic of china': 'TWN',
  'republic of china taiwan': 'TWN',
  'republic of colombia': 'COL',
  'republic of costa rica': 'CRI',
  'republic of cote d ivoire': 'CIV',
  'republic of croatia': 'HRV',
  'republic of cuba': 'CUB',
  'republic of cyprus': 'CYP',
  'republic of djibouti': 'DJI',
  'republic of ecuador': 'ECU',
  'republic of el salvador': 'SLV',
  'republic of equatorial guinea': 'GNQ',
  'republic of estonia': 'EST',
  'republic of fiji': 'FJI',
  'republic of finland': 'FIN',
  'republic of ghana': 'GHA',
  'republic of guatemala': 'GTM',
  'republic of guinea': 'GIN',
  'republic of guinea bissau': 'GNB',
  'republic of haiti': 'HTI',
  'republic of honduras': 'HND',
  'republic of iceland': 'ISL',
  'republic of india': 'IND',
  'republic of indonesia': 'IDN',
  'republic of iraq': 'IRQ',
  'republic of ireland': 'IRL',
  'republic of kazakhstan': 'KAZ',
  'republic of kenya': 'KEN',
  'republic of kiribati': 'KIR',
  'republic of korea': 'KOR',
  'republic of kosovo': 'UNK',
  'republic of latvia': 'LVA',
  'republic of liberia': 'LBR',
  'republic of lithuania': 'LTU',
  'republic of madagascar': 'MDG',
  'republic of malawi': 'MWI',
  'republic of mali': 'MLI',
  'republic of malta': 'MLT',
  'republic of mauritius': 'MUS',
  'republic of moldova': 'MDA',
  'republic of mozambique': 'MOZ',
  'republic of namibia': 'NAM',
  'republic of nauru': 'NRU',
  'republic of nicaragua': 'NIC',
  'republic of niger': 'NER',
  'republic of north macedonia': 'MKD',
  'republic of palau': 'PLW',
  'republic of panama': 'PAN',
  'republic of paraguay': 'PRY',
  'republic of peru': 'PER',
  'republic of poland': 'POL',
  'republic of rwanda': 'RWA',
  'republic of san marino': 'SMR',
  'republic of senegal': 'SEN',
  'republic of serbia': 'SRB',
  'republic of seychelles': 'SYC',
  'republic of sierra leone': 'SLE',
  'republic of singapore': 'SGP',
  'republic of slovenia': 'SVN',
  'republic of south africa': 'ZAF',
  'republic of south sudan': 'SSD',
  'republic of suriname': 'SUR',
  'republic of tajikistan': 'TJK',
  'republic of the congo': 'COG',
  'republic of the gambia': 'GMB',
  'republic of the maldives': 'MDV',
  'republic of the marshall islands': 'MHL',
  'republic of the philippines': 'PHL',
  'republic of the sudan': 'SDN',
  'republic of the union of myanmar': 'MMR',
  'republic of trinidad and tobago': 'TTO',
  'republic of tunisia': 'TUN',
  'republic of turkey': 'TUR',
  'republic of uganda': 'UGA',
  'republic of uzbekistan': 'UZB',
  'republic of vanuatu': 'VUT',
  'republic of yemen': 'YEM',
  'republic of zambia': 'ZMB',
  'republic of zimbabwe': 'ZWE',
  'republica argentina': 'ARG',
  'republica bolivariana de venezuela': 'VEN',
  'republica da guine bissau': 'GNB',
  'republica da guine equatorial': 'GNQ',
  'republica de angola': 'AGO',
  'republica de cabo verde': 'CPV',
  'republica de chile': 'CHL',
  'republica de colombia': 'COL',
  'republica de costa rica': 'CRI',
  'republica de cuba': 'CUB',
  'republica de el salvador': 'SLV',
  'republica de guinea ecuatorial': 'GNQ',
  'republica de honduras': 'HND',
  'republica de mocambique': 'MOZ',
  'republica de nicaragua': 'NIC',
  'republica de panama': 'PAN',
  'republica del ecuador': 'ECU',
  'republica del paraguay': 'PRY',
  'republica del peru': 'PER',
  'republica democratica de sao tome e principe': 'STP',
  'republica democratica de timor leste': 'TLS',
  'republica federativa do brasil': 'BRA',
  'republica moldova': 'MDA',
  'republica oriental del uruguay': 'URY',
  'republica portuguesa': 'PRT',
  'republiek suriname': 'SUR',
  'republik indonesia': 'IDN',
  'republik singapura': 'SGP',
  'republika demokratika timor leste': 'TLS',
  'republika hrvatska': 'HRV',
  'republika ng pilipinas': 'PHL',
  'republika slovenija': 'SVN',
  'republika srbija': 'SRB',
  'republika y uburundi': 'BDI',
  'republiken finland': 'FIN',
  'republique arabe d egypte': 'EGY',
  'republique arabe sahraouie democratique': 'ESH',
  'republique arabe syrienne': 'SYR',
  'republique argentine': 'ARG',
  'republique bolivarienne du venezuela': 'VEN',
  'republique centrafricaine': 'CAF',
  'republique cooperative de guyana': 'GUY',
  'republique d afrique du sud': 'ZAF',
  'republique d albanie': 'ALB',
  'republique d angola': 'AGO',
  'republique d armenie': 'ARM',
  'republique d autriche': 'AUT',
  'republique d azerbaidjan': 'AZE',
  'republique d estonie': 'EST',
  'republique d haiti': 'HTI',
  'republique d indonesie': 'IDN',
  'republique d irak': 'IRQ',
  'republique d irlande': 'IRL',
  'republique d islande': 'ISL',
  'republique d ouzbekistan': 'UZB',
  'republique de bielorussie': 'BLR',
  'republique de bulgarie': 'BGR',
  'republique de chine taiwan': 'TWN',
  'republique de chypre': 'CYP',
  'republique de colombie': 'COL',
  'republique de coree': 'KOR',
  'republique de cote d ivoire': 'CIV',
  'republique de croatie': 'HRV',
  'republique de cuba': 'CUB',
  'republique de djibouti': 'DJI',
  'republique de finlande': 'FIN',
  'republique de gambie': 'GMB',
  'republique de georgie': 'GEO',
  'republique de guinee': 'GIN',
  'republique de guinee bissau': 'GNB',
  'republique de guinee equatoriale': 'GNQ',
  'republique de kiribati': 'KIR',
  'republique de l equateur': 'ECU',
  'republique de l inde': 'IND',
  'republique de l ouganda': 'UGA',
  'republique de l union du myanmar': 'MMR',
  'republique de lettonie': 'LVA',
  'republique de lituanie': 'LTU',
  'republique de macedoine du nord': 'MKD',
  'republique de madagascar': 'MDG',
  'republique de malte': 'MLT',
  'republique de maurice': 'MUS',
  'republique de moldavie': 'MDA',
  'republique de namibie': 'NAM',
  'republique de nauru': 'NRU',
  'republique de pologne': 'POL',
  'republique de saint marin': 'SMR',
  'republique de serbie': 'SRB',
  'republique de sierra leone': 'SLE',
  'republique de singapour': 'SGP',
  'republique de slovenie': 'SVN',
  'republique de trinite et tobago': 'TTO',
  'republique de turquie': 'TUR',
  'republique de vanuatu': 'VUT',
  'republique de zambie': 'ZMB',
  'republique democratique de sao tome et principe': 'STP',
  'republique democratique du congo': 'COD',
  'republique democratique du timor oriental': 'TLS',
  'republique democratique et populaire d algerie': 'DZA',
  'republique democratique populaire lao': 'LAO',
  'republique democratique socialiste du sri lanka': 'LKA',
  'republique des fidji': 'FJI',
  'republique des iles marshall': 'MHL',
  'republique des maldives': 'MDV',
  'republique des palaos palau': 'PLW',
  'republique des philippines': 'PHL',
  'republique des seychelles': 'SYC',
  'republique dominicaine': 'DOM',
  'republique du benin': 'BEN',
  'republique du botswana': 'BWA',
  'republique du burkina': 'BFA',
  'republique du burundi': 'BDI',
  'republique du cameroun': 'CMR',
  'republique du cap vert': 'CPV',
  'republique du chili': 'CHL',
  'republique du congo': 'COG',
  'republique du costa rica': 'CRI',
  'republique du ghana': 'GHA',
  'republique du guatemala': 'GTM',
  'republique du honduras': 'HND',
  'republique du kazakhstan': 'KAZ',
  'republique du kenya': 'KEN',
  'republique du kosovo': 'UNK',
  'republique du liberia': 'LBR',
  'republique du malawi': 'MWI',
  'republique du mali': 'MLI',
  'republique du mozambique': 'MOZ',
  'republique du nepal': 'NPL',
  'republique du nicaragua': 'NIC',
  'republique du niger': 'NER',
  'republique du panama': 'PAN',
  'republique du paraguay': 'PRY',
  'republique du perou': 'PER',
  'republique du rwanda': 'RWA',
  'republique du salvador': 'SLV',
  'republique du senegal': 'SEN',
  'republique du soudan': 'SDN',
  'republique du soudan du sud': 'SSD',
  'republique du suriname': 'SUR',
  'republique du tadjikistan': 'TJK',
  'republique du tchad': 'TCD',
  'republique du yemen': 'YEM',
  'republique du zimbabwe': 'ZWE',
  'republique federale d allemagne': 'DEU',
  'republique federale de somalie': 'SOM',
  'republique federale democratique d ethiopie': 'ETH',
  'republique federale du nigeria': 'NGA',
  'republique federative du bresil': 'BRA',
  'republique francaise': 'FRA',
  'republique gabonaise': 'GAB',
  'republique hellenique': 'GRC',
  'republique islamique d afghanistan': 'AFG',
  'republique islamique d iran': 'IRN',
  'republique islamique de mauritanie': 'MRT',
  'republique islamique du pakistan': 'PAK',
  'republique italienne': 'ITA',
  'republique kirghize': 'KGZ',
  'republique libanaise': 'LBN',
  'republique orientale de l uruguay': 'URY',
  'republique populaire de chine': 'CHN',
  'republique populaire democratique de coree': 'PRK',
  'republique portugaise': 'PRT',
  'republique rwandaise': 'RWA',
  'republique slovaque': 'SVK',
  'republique socialiste du viet nam': 'VNM',
  'republique tcheque': 'CZE',
  'republique togolaise': 'TGO',
  'republique tunisienne': 'TUN',
  'republique unie de tanzanie': 'TZA',
  'repubulika y u rwanda': 'RWA',
  'respublika kazakhstan': 'KAZ',
  'reu': 'REU',
  'reunion': 'REU',
  'reunion island': 'REU',
  'ribaberiki kiribati': 'KIR',
  'ripablik blong vanuatu': 'VUT',
  'ripublik naoero': 'NRU',
  'ro': 'ROU',
  'romania': 'ROU',
  'rou': 'ROU',
  'roumania': 'ROU',
  'roumanie': 'ROU',
  'royaume d arabie saoudite': 'SAU',
  'royaume d espagne': 'ESP',
  'royaume d eswatini': 'SWZ',
  'royaume de bahrein': 'BHR',
  'royaume de belgique': 'BEL',
  'royaume de norvege': 'NOR',
  'royaume de suede': 'SWE',
  'royaume de thailande': 'THA',
  'royaume des tonga': 'TON',
  'royaume du bhoutan': 'BTN',
  'royaume du cambodge': 'KHM',
  'royaume du danemark': 'DNK',
  'royaume du lesotho': 'LSO',
  'royaume du maroc': 'MAR',
  'royaume hachemite de jordanie': 'JOR',
  'royaume uni': 'GBR',
  'royaume uni de grande bretagne et d irlande du nord': 'GBR',
  'rs': 'SRB',
  'rsa': 'ZAF',
  'ru': 'RUS',
  'rumania': 'ROU',
  'rus': 'RUS',
  'russia': 'RUS',
  'russian federation': 'RUS',
  'russie': 'RUS',
  'rw': 'RWA',
  'rwa': 'RWA',
  'rwanda': 'RWA',
  'rzeczpospolita polska': 'POL',
  'sa': 'SAU',
  'sahara occidental': 'ESH',
  'sahrawi arab democratic republic': 'ESH',
  'saint barthelemy': 'BLM',
  'saint christophe et nieves': 'KNA',
  'saint helena': 'SHN',
  'saint helena ascension and tristan da cunha': 'SHN',
  'saint kitts and nevis': 'KNA',
  'saint lucia': 'LCA',
  'saint marin': 'SMR',
  'saint martin': 'SXM',
  'saint martin french part': 'MAF',
  'saint pierre and miquelon': 'SPM',
  'saint pierre et miquelon': 'SPM',
  'saint vincent and the grenadines': 'VCT',
  'saint vincent et les grenadines': 'VCT',
  'sainte helene ascension et tristan da cunha': 'SHN',
  'sainte lucie': 'LCA',
  'sakartvelo': 'GEO',
  'saltanat uman': 'OMN',
  'salvador': 'SLV',
  'samoa': 'WSM',
  'samoa amelika': 'ASM',
  'samoa americaines': 'ASM',
  'san marino': 'SMR',
  'sankattan siha na islas marianas': 'MNP',
  'sao tome and principe': 'STP',
  'sao tome et principe': 'STP',
  'sarnam': 'SUR',
  'sathalanalat paxathipatai paxaxon lao': 'LAO',
  'sau': 'SAU',
  'saudi': 'SAU',
  'saudi arabia': 'SAU',
  'sb': 'SLB',
  'sc': 'SYC',
  'schweiz': 'CHE',
  'sd': 'SDN',
  'sdn': 'SDN',
  'se': 'SWE',
  'sen': 'SEN',
  'senegal': 'SEN',
  'serbia': 'SRB',
  'serbie': 'SRB',
  'seychelles': 'SYC',
  'sg': 'SGP',
  'sgp': 'SGP',
  'sgs': 'SGS',
  'sh': 'SHN',
  'shn': 'SHN',
  'shqiperi': 'ALB',
  'shqiperia': 'ALB',
  'shqipnia': 'ALB',
  'si': 'SVN',
  'sierra leone': 'SLE',
  'singapore': 'SGP',
  'singapour': 'SGP',
  'singapura': 'SGP',
  'sint maarten': 'SXM',
  'sint maarten dutch part': 'SXM',
  'sj': 'SJM',
  'sjm': 'SJM',
  'sk': 'SVK',
  'sl': 'SLE',
  'slb': 'SLB',
  'sle': 'SLE',
  'slovak republic': 'SVK',
  'slovakia': 'SVK',
  'slovaquie': 'SVK',
  'slovenia': 'SVN',
  'slovenie': 'SVN',
  'slovenska republika': 'SVK',
  'slv': 'SLV',
  'sm': 'SMR',
  'smr': 'SMR',
  'sn': 'SEN',
  'so': 'SOM',
  'socialist republic of vietnam': 'VNM',
  'solomon islands': 'SLB',
  'som': 'SOM',
  'somalia': 'SOM',
  'somalie': 'SOM',
  'somers isles': 'BMU',
  'soudan': 'SDN',
  'soudan du sud': 'SSD',
  'south africa': 'ZAF',
  'south georgia': 'SGS',
  'south georgia and the south sandwich islands': 'SGS',
  'south korea': 'KOR',
  'south sudan': 'SSD',
  'spain': 'ESP',
  'spm': 'SPM',
  'sr': 'SUR',
  'sranangron': 'SUR',
  'srb': 'SRB',
  'srbija': 'SRB',
  'sri lanka': 'LKA',
  'ss': 'SSD',
  'ssd': 'SSD',
  'st': 'STP',
  'st barthelemy': 'BLM',
  'st helena ascension and tristan da cunha': 'SHN',
  'state of eritrea': 'ERI',
  'state of israel': 'ISR',
  'state of kuwait': 'KWT',
  'state of libya': 'LBY',
  'state of palestine': 'PSE',
  'state of qatar': 'QAT',
  'stato della citta del vaticano': 'VAT',
  'stp': 'STP',
  'sudan': 'SDN',
  'suede': 'SWE',
  'suid afrika': 'ZAF',
  'suisse': 'CHE',
  'sultanat d oman': 'OMN',
  'sultanate of oman': 'OMN',
  'suomen tasavalta': 'FIN',
  'suomi': 'FIN',
  'sur': 'SUR',
  'surinam': 'SUR',
  'suriname': 'SUR',
  'sv': 'SLV',
  'svalbard and jan mayen': 'SJM',
  'svalbard and jan mayen islands': 'SJM',
  'svalbard et jan mayen': 'SJM',
  'svalbard og jan mayen': 'SJM',
  'svizra': 'CHE',
  'svizzera': 'CHE',
  'svk': 'SVK',
  'svn': 'SVN',
  'swatini': 'SWZ',
  'swaziland': 'SWZ',
  'swe': 'SWE',
  'sweden': 'SWE',
  'swiss confederation': 'CHE',
  'switzerland': 'CHE',
  'swz': 'SWZ',
  'sx': 'SXM',
  'sxm': 'SXM',
  'sy': 'SYR',
  'syc': 'SYC',
  'syr': 'SYR',
  'syria': 'SYR',
  'syrian arab republic': 'SYR',
  'syrie': 'SYR',
  'sz': 'SWZ',
  'tadjikistan': 'TJK',
  'taiwan': 'TWN',
  'tajikistan': 'TJK',
  'tanezroft tutrimt': 'ESH',
  'tanzania': 'TZA',
  'tanzania united republic of': 'TZA',
  'tanzanie': 'TZA',
  'tc': 'TCA',
  'tca': 'TCA',
  'tcd': 'TCD',
  'tchad': 'TCD',
  'tchequie': 'CZE',
  'td': 'TCD',
  'teratri of norf k ailen': 'NFK',
  'terres australes et antarctiques francaises': 'ATF',
  'territoire britannique de l ocean indien': 'IOT',
  'territoire de l ile christmas': 'CXR',
  'territoire de l ile norfolk': 'NFK',
  'territoire des iles cocos keeling': 'CCK',
  'territoire des iles wallis et futuna': 'WLF',
  'territoire des terres australes et antarctiques francaises': 'ATF',
  'territory of christmas island': 'CXR',
  'territory of norfolk island': 'NFK',
  'territory of the cocos keeling islands': 'CCK',
  'territory of the french southern and antarctic lands': 'ATF',
  'territory of the wallis and futuna islands': 'WLF',
  'teta paraguai': 'PRY',
  'teta volivia': 'BOL',
  'tf': 'ATF',
  'tg': 'TGO',
  'tgo': 'TGO',
  'th': 'THA',
  'tha': 'THA',
  'thai': 'THA',
  'thailand': 'THA',
  'thailande': 'THA',
  'the abode of peace': 'BRN',
  'the bermudas': 'BMU',
  'the former yugoslav republic of macedonia': 'MKD',
  'the islands of bermuda': 'BMU',
  'the netherlands': 'NLD',
  'timor leste': 'TLS',
  'timor lorosa e': 'TLS',
  'timor lorosae': 'TLS',
  'timor oriental': 'TLS',
  'tj': 'TJK',
  'tjk': 'TJK',
  'tk': 'TKL',
  'tkl': 'TKL',
  'tkm': 'TKM',
  'tl': 'TLS',
  'tls': 'TLS',
  'tm': 'TKM',
  'tn': 'TUN',
  'to': 'TON',
  'tocikiston': 'TJK',
  'togo': 'TGO',
  'togolese': 'TGO',
  'togolese republic': 'TGO',
  'tokelau': 'TKL',
  'ton': 'TON',
  'tonga': 'TON',
  'tr': 'TUR',
  'trinidad and tobago': 'TTO',
  'trinite et tobago': 'TTO',
  'tt': 'TTO',
  'tto': 'TTO',
  'tun': 'TUN',
  'tunisia': 'TUN',
  'tunisian republic': 'TUN',
  'tunisie': 'TUN',
  'tur': 'TUR',
  'turkey': 'TUR',
  'turkiye': 'TUR',
  'turkiye cumhuriyeti': 'TUR',
  'turkmenistan': 'TKM',
  'turks and caicos islands': 'TCA',
  'turquie': 'TUR',
  'tuv': 'TUV',
  'tuvalu': 'TUV',
  'tv': 'TUV',
  'tw': 'TWN',
  'twn': 'TWN',
  'tz': 'TZA',
  'tza': 'TZA',
  'ua': 'UKR',
  'uae': 'ARE',
  'udzima wa komori': 'COM',
  'ug': 'UGA',
  'uga': 'UGA',
  'uganda': 'UGA',
  'uk': 'GBR',
  'ukr': 'UKR',
  'ukraine': 'UKR',
  'ukrayina': 'UKR',
  'um': 'UMI',
  'umbuso weswatini': 'SWZ',
  'umi': 'UMI',
  'union des comores': 'COM',
  'union of the comoros': 'COM',
  'united arab emirates': 'ARE',
  'united kingdom': 'GBR',
  'united kingdom of great britain and northern ireland': 'GBR',
  'united mexican states': 'MEX',
  'united republic of tanzania': 'TZA',
  'united states': 'USA',
  'united states minor outlying islands': 'UMI',
  'united states of america': 'USA',
  'united states virgin islands': 'VIR',
  'unk': 'UNK',
  'uruguay': 'URY',
  'ury': 'URY',
  'us': 'USA',
  'usa': 'USA',
  'uy': 'URY',
  'uz': 'UZB',
  'uzb': 'UZB',
  'uzbekistan': 'UZB',
  'va': 'VAT',
  'vanuatu': 'VUT',
  'vat': 'VAT',
  'vatican city': 'VAT',
  'vatican city state': 'VAT',
  'vc': 'VCT',
  'vct': 'VCT',
  've': 'VEN',
  'ven': 'VEN',
  'venezuela': 'VEN',
  'venezuela bolivarian republic of': 'VEN',
  'vg': 'VGB',
  'vgb': 'VGB',
  'vi': 'VIR',
  'viet nam': 'VNM',
  'vietnam': 'VNM',
  'vir': 'VIR',
  'virgin islands': 'VGB',
  'virgin islands british': 'VGB',
  'virgin islands of the united states': 'VIR',
  'virgin islands u s': 'VIR',
  'viti': 'FJI',
  'vn': 'VNM',
  'vnm': 'VNM',
  'vu': 'VUT',
  'vut': 'VUT',
  'wai tu kubuli': 'DMA',
  'wallis and futuna': 'WLF',
  'wallis et futuna': 'WLF',
  'western sahara': 'ESH',
  'weswatini': 'SWZ',
  'wf': 'WLF',
  'wlf': 'WLF',
  'ws': 'WSM',
  'wsm': 'WSM',
  'wuliwya': 'BOL',
  'wuliwya suyu': 'BOL',
  'xk': 'UNK',
  'ye': 'YEM',
  'yem': 'YEM',
  'yemen': 'YEM',
  'yemeni republic': 'YEM',
  'yt': 'MYT',
  'za': 'ZAF',
  'zaf': 'ZAF',
  'zambia': 'ZMB',
  'zambie': 'ZMB',
  'zhongguo': 'CHN',
  'zhonghua': 'CHN',
  'zhonghua minguo': 'TWN',
  'zhonghua renmin gongheguo': 'CHN',
  'zimbabwe': 'ZWE',
  'zm': 'ZMB',
  'zmb': 'ZMB',
  'zw': 'ZWE',
  'zwe': 'ZWE',
};
