name: rwa_calculator
description: Base Flutter modulaire pour un outil RWA.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  archive: ^3.6.1
  desktop_drop: ^0.7.0
  excel: ^4.0.6
  file_selector: ^1.0.3
  http: ^1.2.2
  intl: ^0.20.2
  lottie: ^3.1.2
  pdf: ^3.11.1
  flutter_svg: ^2.0.10+1
  flutter_math_fork: ^0.7.4
  xml: ^6.6.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/heymanns_logo.png
    - assets/images/logo.png
    - assets/images/logo_header.png
    - assets/images/risk_management.png
    - assets/images/rwa_credit.png
    - assets/images/manage_money_bro.svg
    - assets/flags/
    - assets/lotties/import_loader.json
    - assets/lotties/rwa_dashboard.json
    - assets/lotties/yield_curve_no_data.json
  fonts:
    - family: Tenor Sans
      fonts:
        - asset: assets/fonts/TenorSans-Regular.ttf
    - family: General Sans
      fonts:
        - asset: assets/fonts/GeneralSans-Extralight.otf
          weight: 200
        - asset: assets/fonts/GeneralSans-ExtralightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/GeneralSans-Light.otf
          weight: 300
        - asset: assets/fonts/GeneralSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/GeneralSans-Regular.otf
          weight: 400
        - asset: assets/fonts/GeneralSans-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/GeneralSans-Medium.otf
          weight: 500
        - asset: assets/fonts/GeneralSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/GeneralSans-Semibold.otf
          weight: 600
        - asset: assets/fonts/GeneralSans-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/GeneralSans-Bold.otf
          weight: 700
        - asset: assets/fonts/GeneralSans-BoldItalic.otf
          weight: 700
          style: italic
