name: rwa_calculator
description: Base Flutter modulaire pour un outil RWA.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  desktop_drop: ^0.7.0
  file_selector: ^1.0.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.20.2
  lottie: ^3.1.2
  pdf: ^3.11.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/heymanns_logo.png
    - assets/images/rwa_credit.png
    - assets/images/manage_money_bro.svg
    - assets/lotties/import_loader.json
    - assets/lotties/rwa_dashboard.json
